### ISSUE TITLE
Linux Error

### ISSUE THREAD

**Issue by ComoSgt** [auroramod/iw7-mod#108]
I've been testing the mod on my Deck and it's still throwing the same error. I attempted to add a "steam_path.txt" in the root directory and tried various paths but it still throws the same error. I also tried adding the "-nosteam" launch command to see if that would possibly work as well as different protons and such but unfortunately, it's not very different than it was before. 

The error:
Fatal error (0xC0000005) at 0x00000001605D5030.

**Comment by ComoSgt** [comment]
[iw7mod-crash-2024-01-26-22-17-12.zip](https://github.com/Joelrau/iw7-mod/files/14071006/iw7mod-crash-2024-01-26-22-17-12.zip)

here is one of the minidumps. i don't know why i keep getting an access violation error. i've tried making sure the entire folder can be read and written into, doesn't change anything.

**Comment by mjkzy** [comment]
join Discord @ https://discord.com/invite/RzzXu5EVnh and @ me (my name is @mjkzy) and i can help you in iw7 support
