### ISSUE TITLE
Game don't Start

### ISSUE THREAD

**Issue by RywaZ** [auroramod/iw7-mod#119]
Hi when i want to launch the iw7-mod.exe the console spawn but the game close instantly

**Comment by RywaZ** [comment]
i have the game on steam

**Comment by RywaZ** [comment]
https://streamable.com/kq86j0

**Comment by mjkzy** [comment]
this might be a windows 11 issue. just in case, try https://chse.dev/redists and then do it again.

**Comment by RywaZ** [comment]
> this might be a windows 11 issue. just in case, try https://chse.dev/redists and then do it again.

Ok thanks i will try this

**Comment by RywaZ** [comment]
> this might be a windows 11 issue. just in case, try https://chse.dev/redists and then do it again.

I have the same issue old iw7 build work but the new don't work

**Comment by mjkzy** [comment]
antiviruses?

**Comment by RywaZ** [comment]
> antiviruses?

no i don't have any antivirus on my pc

**Comment by mjkzy** [comment]
im not too sure. join the discord at https://discord.com/invite/RzzXu5EVnh and @ me (my name is @mjkzy) and i can try to help more in depth in h1 support
