### ISSUE TITLE
Crashing after awhile 

### ISSUE THREAD

**Issue by Nova405** [auroramod/iw7-mod#125]
Game kept crashing after some time so i took the error dump into VS and hooked into IW and this code keeps causing an Access Violation error

Error: Exception thrown at 0x0000000140733C90 (iw7_ship.exe) in iw7-mod.exe: 0xC0000005: Access violation reading location 0x000000000000088C.

Code (in fike hook.hpp):
`T invoke(Args ... args)
{
	return static_cast<T(*)(Args ...)>(this->get_original())(args...);
}`
line 140-143

![image](https://github.com/auroramod/iw7-mod/assets/108157895/1500bcc2-cd10-4a0c-a628-f7fb6468c23f)

**Comment by mjkzy** [comment]
if its being stopped at invoke, sounds like you can get a stack trace if you debug it right and breakpoint. ill check the address though inna bit

**Comment by Nova405** [comment]
alright, id like to add i do have cheat engine for use with a table and that does seem like it could be one of the factors to it, although im not sure as i haven't done extensive use without the table

**Comment by mjkzy** [comment]
you seem to be crashing in `BG_GetViewmodelWeapon`, which could indicate a corrupt player state or something bad happening. it may be your cheat engine though, i couldn't tell you for sure.

![image](https://github.com/auroramod/iw7-mod/assets/64374267/20f1792f-4531-46d5-9971-50be18355812)

**Comment by Nova405** [comment]
Ah, it might be the no recoil script, I’d have to look at the code for it but that’s probably it, thank you and I’ll try testing when I’m off work
