### ISSUE TITLE
Fortune Cards Zombie

### ISSUE THREAD

**Issue by RywaZ** [auroramod/iw7-mod#169]
Hello, I wanted to know if there was a way to change the number of fortune cards you have because you only have 1 and after using them in a game the cards reset so you have to put them back each time.
![Screenshot_1](https://github.com/auroramod/iw7-mod/assets/124745850/dc77f393-74f2-4835-be63-45d7ce6cbb21)

**Comment by mjkzy** [comment]
not a immediate issue, so gonna close.

however, you can find it here at https://github.com/auroramod/iw7-mod/blob/main/src/client/component/stats.cpp at line 50. it's hardcoded to 1 but you can make it whatever you want. if you'd like to make a PR to increase the amount, feel free 🙂

**Comment by RywaZ** [comment]
> not a immediate issue, so gonna close.
> 
> however, you can find it here at https://github.com/auroramod/iw7-mod/blob/main/src/client/component/stats.cpp at line 50. it's hardcoded to 1 but you can make it whatever you want. if you'd like to make a PR to increase the amount, feel free 🙂

Thanks you
