### ISSUE TITLE
Fatal Error: Content package is no longer available.

### ISSUE THREAD

**Issue by LeftoverAtoms** [auroramod/iw7-mod#177]
![image](https://github.com/auroramod/iw7-mod/assets/66341882/e27b4ccd-96be-45d9-96a8-eb199513c254)
![image](https://github.com/auroramod/iw7-mod/assets/66341882/7a0a77ea-e174-4dbe-99c9-984293f31fc7)

I did include the --dev-build flag.

**Comment by mjkzy** [comment]
corrupted files, not related to us

**Comment by LeftoverAtoms** [comment]
> corrupted files, not related to us

It was a fresh install?

**Comment by mjkzy** [comment]
for starters, you're getting a invalid game file error when opening. that doesn't just happen :P that should be your warning that your files are bad

and to further prove it, the content package error means the fastfile its trying to load cannot be found or its corrupted

either reinstall or verify your files
