### ISSUE TITLE
Add a gsc file

### ISSUE THREAD

**Issue by Darkseid-vrr** [auroramod/iw7-mod#188]
Hi, thank you very much for your work. I have been following your project for over a year.  develop solutions on my side and see the improvement and additions you have made.  it's really awesome.

I work on scripts and errors on dedicated servers and also reading gsc file.  After multiple attempts I cannot execute a gsc file.
Is there a solution currently or not?  What thing am I missing?  or what can I work on to help?
DCACHE files are additionally created next to the gsc also after launching the server.
Thank you very much in advance for taking the time to read me and possibly provide answers
![Capture d'écran 2024-04-04 174737](https://github.com/auroramod/iw7-mod/assets/161222416/b80465a3-e51d-41d0-b2e6-403d5e39687c)
![Capture d'écran 2024-04-04 174820](https://github.com/auroramod/iw7-mod/assets/161222416/ccd55eba-4b41-4feb-8035-051e9816e889)

**Comment by mjkzy** [comment]
gsc files are used at `iw7-mod/custom_scripts/zm_mymod.gsc` or `iw7-mod/scripts/mp/gametypes/dm.gsc` for overriding stock

**Comment by Darkseid-vrr** [comment]
Thank you so much. in the meantime I made a "scripts" folder in the path of the game and it worked too.
