### ISSUE TITLE
2 errors when trying to build

### ISSUE THREAD

**Issue by Sguffey82** [auroramod/iw7-mod#233]
So the previous issue i had i was able to fix but everytime i try and build the solution i get these 2 errors.  Im not sure how to fix them tried unistalling and reinstalling the game but didnt work
![Screenshot 2024-05-04 125514](https://github.com/auroramod/iw7-mod/assets/90367626/e488cf52-708f-4010-8258-1b3446a4ce78)

**Comment by Arrhythmia** [comment]
Install Git for your Windows, delete the Build folder that you generated, run generate.bat again and try to build again.

**Comment by Sguffey82** [comment]
Ty so much I couldnt for the life of me figure out what the problem worked like a charm u can close this one and the one before that i posted ty
