### ISSUE TITLE
Unable to build solution(errors)

### ISSUE THREAD

**Issue by FIyynn** [auroramod/iw7-mod#274]
I followed all the steps to compile the IW7-Mod but encountered an error when building. Git is installed and i own the game on steam.
Here are the commands i followed:
[Powershell output.txt](https://github.com/user-attachments/files/16036449/commands.output.txt)

1. Cloned the Repository:
   git clone https://github.com/auroramod/iw7-mod.git
   cd iw7-mod

2. Updated Submodules:
   git submodule update --init --recursive

3. Generated Project Files Using the Provided Batch File:
   ./generate.bat

4. Opened and Built the Solution in Visual Studio:
   iw7-mod.sln

But the build process resulted in an error:

Rebuild All: 15 succeeded, 1 failed, 0 skipped 
Rebuild completed at 11:42 AM and took 27.761 seconds

Errors:
Severity    Code    Description    Project    File    Line
Error    C2039    'first': is not a member of 'std::tuple<xsk::gsc::buffer,xsk::gsc::buffer,xsk::gsc::buffer>'    client    src\client\component\gsc\script_loading.cpp    152
Error    C2737    'bytecode': const object must be initialized    client    src\client\component\gsc\script_loading.cpp    152
Error    C2039    'second': is not a member of 'std::tuple<xsk::gsc::buffer,xsk::gsc::buffer,xsk::gsc::buffer>'    client    src\client\component\gsc\script_loading.cpp    153
Error    C2737    'stack': const object must be initialized    client    src\client\component\gsc\script_loading.cpp    153
Error    C3536    'stack': cannot be used before it is initialized    client    src\client\component\gsc\script_loading.cpp    158
Error    C3536    'bytecode': cannot be used before it is initialized    client    src\client\component\gsc\script_loading.cpp    159
Error    C2737    'stack_size': const object must be initialized    client    src\client\component\gsc\script_loading.cpp    161
Error    C2737    'byte_code_size': const object must be initialized    client    src\client\component\gsc\script_loading.cpp    162
Error    C3536    'stack_size': cannot be used before it is initialized    client    src\client\component\gsc\script_loading.cpp    164
Error    C2660    'memcpy': function does not take 1 argument    client    src\client\component\gsc\script_loading.cpp    165
Error    C3536    'byte_code_size': cannot be used before it is initialized    client    src\client\component\gsc\script_loading.cpp    167
Error    C2660    'memcpy': function does not take 1 argument    client    src\client\component\gsc\script_loading.cpp    168
Error    C2664    'void xsk::gsc::context::init(xsk::gsc::build,xsk::gsc::context::fs_callback)': cannot convert argument 2 from 'gsc::`anonymous-namespace'::init_compiler::<lambda_1>' to 'xsk::gsc::context::fs_callback'    client    src\client\component\gsc\script_loading.cpp    296

Please let me know if i made a mistake
And is it possible to provide a release version of the mod?

**Comment by mjkzy** [comment]
try the latest commit - are you still erroring?

**Comment by FIyynn** [comment]
i got less errors this time:
2 errors, the bin file still only has the runner.exe and the dll. The folder is missing the mod exe.
i re-followed these steps
[new powershell output.txt](https://github.com/user-attachments/files/16037102/powershell.output.txt)
[vscode build output.txt](https://github.com/user-attachments/files/16037128/vscode.build.output.txt)
![image](https://github.com/auroramod/iw7-mod/assets/53620674/cfc7a7b6-4cc3-4ba9-849e-bf069e2662e4)

**Comment by Joelrau** [comment]
try again

**Comment by FIyynn** [comment]
everything works now thank you

**Comment by Spirituxl** [comment]
im having the same two errors. how would i get about this? what exactly should i 'try again'

**Comment by FIyynn** [comment]
> im having the same two errors. how would i get about this? what exactly should i 'try again'

It was updated, redo the whole process.
re-clone the repo and start from there again
