### ISSUE TITLE
crc32 already defined error when trying to build

### ISSUE THREAD

**Issue by TheRealBossRPG** [auroramod/iw7-mod#344]
I am pretty sure I have done everything correctly, I have tried multiple times to clone/delete the build that were generated in the process but I can't seem to get it working, I have vs 2022 and GIT aswell, not sure what's going on and Ive skimmed through the issues both open and closed and I haven't seen this so I hope it isnt something on my end, this is my
![image](https://github.com/user-attachments/assets/753f615c-5b88-48fd-982c-a34f40a21958)

**Comment by EngineersBox** [comment]
Note that if you already have zlib, through some lib management (or directly managed) you'll want to remove it. In my case I had it as a dependency of some libs via vcpkg so I uninstalled those deps temporarily to build this and then reinstalled it later.

Check if you have anything installed, look for `zlib:x64-windows` or `zlib:x86-windows`
```shell
vcpkg list
```

Uninstall them (they may be tied to other deps, so run with `--recuse` if so, noting the parent dependencies so you can reinstall them later):
```shell
vcpkg remove --recuse zlib:x64-windows
```

**Comment by TheRealBossRPG** [comment]
> Note that if you already have zlib, through some lib management (or directly managed) you'll want to remove it. In my case I had it as a dependency of some libs via vcpkg so I uninstalled those deps temporarily to build this and then reinstalled it later.
> 
> Check if you have anything installed, look for `zlib:x64-windows` or `zlib:x86-windows`
> 
> ```shell
> vcpkg list
> ```
> 
> Uninstall them (they may be tied to other deps, so run with `--recuse` if so, noting the parent dependencies so you can reinstall them later):
> 
> ```shell
> vcpkg remove --recuse zlib:x64-windows
> ```

Awesome, that worked, I had zlib installed for x64 and x86 for my sfml development and it seems that was the issue, I uninstalled them then built and everything is fine now, thank you very much!
